Feature/weekly updates
nir2002/ganyeledteva-gatsby pull request #1
Opened 2021-05-18 17:40 UTC by IdanSchiller

2021-05-19 07:14 UTC, nir2002 requested changes

2021-05-19 07:14 UTC, nir2002 commented on tailwind.config.js
> +        nonmob : '768px',
why do you need it? Tailwind method is to design mobile first and then set styles for all other screens

2021-05-19 07:14 UTC, nir2002 commented on tailwind.config.js
> +        purpleBorder : '#f7479e',
why not just purple and red? we can use it in multiple places
and actually, I think we should create a theme with the main website colors

2021-05-19 07:14 UTC, nir2002 commented on src/templates/weekly-update.jsx
> +                  <img className="h-full" src={"/logos/logo.png"} alt="Logo" />
Can we create a logo component that will be used across the project?
Pay attention I'm using logo in HomeHeader component as well.

2021-05-19 07:14 UTC, nir2002 commented on src/templates/weekly-update.jsx
> +                  {restPostList.map((post, indx) => (
indx -> index
Basically I don't like shortcut, but if you want to use it then call it `idx`

2021-05-19 07:14 UTC, nir2002 commented on src/templates/weekly-update.jsx
> +                    indx < 8 && //render only 8 items
when writing a comment, write why you do it and now what you are doing, since what you are doing is referred fro your code

2021-05-19 07:14 UTC, nir2002 commented on src/templates/weekly-update.jsx
> +const PostItem = ({ date, title, link }) => {
Lets call link in a more informative name, something like `fullPostUrl`

2021-05-19 07:14 UTC, nir2002 commented on src/templates/weekly-update.jsx
> +const Row = ({ children, height, mb, withLeftGap }) => {
And by the way, doesn't tailwind have something like this?

2021-05-19 07:14 UTC, nir2002 commented on src/templates/weekly-update.jsx
> +          <p className="mb-4">{moment(firstPost.date).format("DD/MM/YYYY")}</p>
use the suggest function from before (the one I said to move to utils)

2021-05-19 07:14 UTC, nir2002 commented on gatsby-node.js
> +  // const postsEdges = markdownQueryResult.data.allMarkdownRemark.edges;
remove if not used anymore

2021-05-19 07:14 UTC, nir2002 commented on gatsby-node.js
> +    path: `/weekly-update`,
I suggest we'll create a routes files with all the paths and even components, that's on me, I'll open a task for that

2021-05-19 08:42 UTC, IdanSchiller commented on src/components/PostListing/PostListing.jsx
> +      dir: postEdge.node.fields.dir
This is the "dir" field for each post so we could filter the GraphQL query to only retrieve posts of a certain directory (i.e. "weekly-updates"), instead of querying all .md file and then filter them.

2021-05-19 08:43 UTC, IdanSchiller commented on src/styles/global.css
> +    @apply block;
My mistake, deleted.

2021-05-19 08:43 UTC, IdanSchiller commented on src/templates/post.css
> +  @screen sm {
My mistake, deleted.

2021-05-19 08:43 UTC, IdanSchiller commented on src/templates/post.jsx
> +// import './post.css';
My mistake, deleted.

2021-05-19 08:54 UTC, IdanSchiller commented on src/templates/post.jsx
> +        {/* <SEO postPath={slug} postNode={postNode} postSEO /> */}
My mistake again. There was a problem where the post.frontmatter didn't had a "cover" field and the following line
"getImagePath(image)" (SEO 48)
caused an error, because "image" was undefined. (image = post.frontmatter.cover)
I've added a check to see if "image==undefined" before calling the "getImagePath".
do you think we should move this check to appear inside "getImagePath" function?

2021-05-19 09:02 UTC, IdanSchiller commented on src/templates/post.jsx
> +            subtitle={moment(post.date).format("DD/MM/YYYY")}
Done

2021-05-19 09:03 UTC, IdanSchiller commented on src/templates/post.jsx
> +                {/* <div dangerouslySetInnerHTML={{ __html: postNode.html }} /> */}
deleted

2021-05-19 09:03 UTC, IdanSchiller commented on src/templates/post.jsx
> +          {/* <Disqus postNode={postNode} /> */}
My mistake, I've uncommented it

2021-05-19 09:03 UTC, IdanSchiller commented on src/templates/post.jsx
> +}
Done

2021-05-19 09:04 UTC, IdanSchiller commented on src/templates/post.jsx
> + <blockquote {...props} className='relative p-4 italic border-r-4 bg-neutral-100 text-neutral-600 border-neutral-500 quote'>
My mistake, deleted "relative".

2021-05-19 09:32 UTC, IdanSchiller commented on tailwind.config.js
> +        nonmob : '768px',
OK I see now that I miss understood something, I removed the "nonmob" breakpoint and changed it toback to "md" breakpoint

2021-05-19 09:35 UTC, IdanSchiller commented on tailwind.config.js
> +        purpleBorder : '#f7479e',
I did it so it wouldn't overwrite the default purple or something like that... I can change their names to "purple" and "red" and use it as the default theme colors of the website

2021-05-19 10:26 UTC, IdanSchiller commented on src/templates/weekly-update.jsx
> +                  <img className="h-full" src={"/logos/logo.png"} alt="Logo" />
you mean a component that returns an <img> element? or just the path to the logo image?

2021-05-19 10:27 UTC, IdanSchiller commented on src/templates/weekly-update.jsx
> +                      filter: { fields: { dir: { eq: "weekly-update" }}}) {
I'm not quite sure what you mean, you mean shorter/prettier syntax for filtering?

2021-05-19 10:27 UTC, IdanSchiller commented on src/templates/weekly-update.jsx
> +                  {restPostList.map((post, indx) => (
changed it to "index"

2021-05-19 10:28 UTC, IdanSchiller commented on src/templates/weekly-update.jsx
> +                    indx < 8 && //render only 8 items
Will do. deleted this comments

2021-05-19 10:28 UTC, IdanSchiller commented on src/templates/weekly-update.jsx
> +const PostItem = ({ date, title, link }) => {
Done, is now called "fullPostUrl" and I'll remember to use more informative names from now on.

2021-05-19 10:29 UTC, IdanSchiller commented on src/templates/weekly-update.jsx
> +          <p className="mb-4">{moment(firstPost.date).format("DD/MM/YYYY")}</p>
Done.

2021-05-19 10:29 UTC, IdanSchiller commented on gatsby-node.js
> +  // const postsEdges = markdownQueryResult.data.allMarkdownRemark.edges;
Done.

2021-05-19 10:36 UTC, IdanSchiller commented on src/templates/weekly-update.jsx
> +const Row = ({ children, height, mb, withLeftGap }) => {
I didn't encountered something like this in tailwind, do you have something in mind?
I see other pages has similar but not the exact row layout (some have 3 divs, some have 5 and so on...)
I can try to write a more generic row component or make a custom row for each page (if needed), which way you prefer.

2021-05-19 11:03 UTC, nir2002 requested changes

2021-05-19 11:03 UTC, nir2002 commented on src/templates/weekly-update.jsx
> +                  <img className="h-full" src={"/logos/logo.png"} alt="Logo" />
a component that will return an element (img)
and of course will be customisable, maybe using `size` prop and of course the option to send classes and style

2021-05-19 11:03 UTC, nir2002 commented on src/templates/weekly-update.jsx
> +    // <div className="md:w-9/10 box-border border-2 mb-5 h-80 float-right hover:border-purpleBorder">
delete if not used

2021-05-19 11:03 UTC, nir2002 commented on src/templates/weekly-update.jsx
> +const Row = ({ children, height, mb, withLeftGap }) => {
what about this?
https://tailwindcss.com/docs/grid-template-columns

2021-05-19 11:03 UTC, nir2002 commented on tailwind.config.js
> +        purpleBorder : '#f7479e',
I think its better, dont you think?

2021-05-19 11:06 UTC, IdanSchiller commented on src/templates/post.jsx
> +// This should be the weekly-update post page
Good Idea, done.

2021-05-20 08:04 UTC, IdanSchiller reviewed
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1)* status: 0 of 178 files reviewed, 23 unresolved discussions (waiting on @apply, @IdanSchiller, and @nir2002)

___
*[src/templates/weekly-update.jsx, line 50 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-Ma06i4_9pyONvZokwCC-r2-50:-Ma7mfK0CWhZ8a3pWHkM:buuozcg) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e826f742444a066da328b01759c0bb95b97522a1/src/templates/weekly-update.jsx#L50)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

a component that will return an element (img)
and of course will be customisable, maybe using `size` prop and of course the option to send classes and style
</blockquote></details>

I've created a Logo element, and props can be passed to it as well
___
*[src/templates/weekly-update.jsx, line 99 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-Ma06i4_9pyONvZokwCC-r2-99:-Ma7nBnSDJ2RPUoZmtqN:bnc3ngt) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e826f742444a066da328b01759c0bb95b97522a1/src/templates/weekly-update.jsx#L99)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

what about this?
https://tailwindcss.com/docs/grid-template-columns
</blockquote></details>

changed the page layout to use gird
___
*[src/templates/weekly-update.jsx, line 82 at r3](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-Ma06i4_9pyONvZokwCC-r3-82:-Ma7n9p04IbHjpsjpPUz:bb6un1j) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/d02d7ed2fb1adcde269d821dc52dbb12acffe30a/src/templates/weekly-update.jsx#L82)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

delete if not used
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-05-20 11:54 UTC, nir2002 requested changes
> Reviewed 16 of 129 files at r1, 120 of 157 files at r2, 35 of 40 files at r3, 1 of 3 files at r4, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1)* status: all files reviewed, 7 unresolved discussions (waiting on @IdanSchiller)

___
*[src/templates/post.jsx, line 19 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-Ma06i4_9pyONvZokwCB-r2-19:-Ma8aRJqEbEtTyfwRHAB:b-1bnmlr) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e826f742444a066da328b01759c0bb95b97522a1/src/templates/post.jsx#L19)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

Good Idea, done.
</blockquote></details>

You need to change the function name as well
___
*[src/templates/post.jsx, line 34 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-Ma06i4_9pyONvZokwCB-r2-34:-Ma8brJD9KH5xieqm_PE:b-xdphl7) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e826f742444a066da328b01759c0bb95b97522a1/src/templates/post.jsx#L34)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

My mistake again. There was a problem where the post.frontmatter didn't had a "cover" field and the following line
"getImagePath(image)" (SEO 48)
caused an error, because "image" was undefined. (image = post.frontmatter.cover)
I've added a check to see if "image==undefined" before calling the "getImagePath".
do you think we should move this check to appear inside "getImagePath" function?
</blockquote></details>

Nope, what you did is good
We need to validate that we send a valid parameter to the function

In the future we will add TypeScript so it will protect us
___
*[src/templates/WeeklyUpdatePostTemplate.jsx, line 42 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-Ma8acNyEWdHQZoBCXqb:-Ma8acNyEWdHQZoBCXqc:buovz9j) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0ce0d64798214c9a0748fe8aa0d253b387d3bc9a/src/templates/WeeklyUpdatePostTemplate.jsx#L42)):*
> ```JavaScript
>           <Page.Main>
>             <div className="flex justify-between">
>               <div className="hidden md:block w-1/5 RIGHT_GAP"/>
> ```

so what is this RIGHT_GAP and is it in upper case letters?
___
*[src/templates/WeeklyUpdatePostTemplate.jsx, line 43 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-Ma8ai1u4b-yBcU4E6NB:-Ma8ai1u4b-yBcU4E6NC:bozid7j) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0ce0d64798214c9a0748fe8aa0d253b387d3bc9a/src/templates/WeeklyUpdatePostTemplate.jsx#L43)):*
> ```JavaScript
>             <div className="flex justify-between">
>               <div className="hidden md:block w-1/5 RIGHT_GAP"/>
>               <div className="md:w-3/5 mb-10 MAIN_CONTENT">
> ```

same for MAIN_CONTENT
___
*[src/templates/weekly-update.jsx, line 132 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-Ma06i4_9pyONvZokwCC-r2-132:-Ma8bCZ96yCNbVqDwgnO:b-iwayle) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e826f742444a066da328b01759c0bb95b97522a1/src/templates/weekly-update.jsx#L132)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

I'm not quite sure what you mean, you mean shorter/prettier syntax for filtering?
</blockquote></details>

its an extension
https://prettier.io/


<!-- Sent from Reviewable.io -->

2021-05-20 15:25 UTC, IdanSchiller reviewed
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1)* status: all files reviewed, 7 unresolved discussions (waiting on @nir2002)

___
*[gatsby-node.js, line 102 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-Ma06i4_9pyONvZokwC7-r2-102:-Ma9N6cH97GqoYTVGQN5:bkjxpv0) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e826f742444a066da328b01759c0bb95b97522a1/gatsby-node.js#L102)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

I suggest we'll create a routes files with all the paths and even components, that's on me, I'll open a task for that
</blockquote></details>

alright
___
*[src/templates/weekly-update.jsx, line 67 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-Ma06i4_9pyONvZokwCC-r2-67:-Ma9NJp-8hCtQel6yr04:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e826f742444a066da328b01759c0bb95b97522a1/src/templates/weekly-update.jsx#L67)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

Will do. deleted this comments
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-20 16:45 UTC, nir2002 requested changes
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1)* status: all files reviewed, 4 unresolved discussions (waiting on @IdanSchiller)

___
*[src/templates/WeeklyUpdatePostTemplate.jsx, line 42 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-Ma8acNyEWdHQZoBCXqb:-Ma9eaO_DdxgIFqtEgCr:b-k4z1wq) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0ce0d64798214c9a0748fe8aa0d253b387d3bc9a/src/templates/WeeklyUpdatePostTemplate.jsx#L42)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

it is the actual name of this container, to understand what is it part in the layout, should I remove it?
</blockquote></details>

as discussed
___
*[src/templates/WeeklyUpdatePostTemplate.jsx, line 43 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-Ma8ai1u4b-yBcU4E6NB:-Ma9ebtwCjOjd-GrKcMV:beztulw) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0ce0d64798214c9a0748fe8aa0d253b387d3bc9a/src/templates/WeeklyUpdatePostTemplate.jsx#L43)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

same
</blockquote></details>

as discussed
___
*[src/templates/weekly-update.jsx, line 67 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-Ma06i4_9pyONvZokwCC-r2-67:-Ma9bqhsDKIaxFWrMHMR:bxsf0ls) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e826f742444a066da328b01759c0bb95b97522a1/src/templates/weekly-update.jsx#L67)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I checked in the code, its still there.
___
*[src/templates/weekly-update.jsx, line 132 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-Ma06i4_9pyONvZokwCC-r2-132:-Ma9dcZE-WXDk7T7X7M0:bctr8qy) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e826f742444a066da328b01759c0bb95b97522a1/src/templates/weekly-update.jsx#L132)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

cool, I will check it out
</blockquote></details>

Its a must :) and already configured in the project
___
*[src/templates/weekly-update.jsx, line 75 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-Ma9c3-_EjkTJudhlFNH:-Ma9c3-_EjkTJudhlFNI:b2wgv91) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/f74bbd42cba67a00f0524546c060a50b65c855ac/src/templates/weekly-update.jsx#L75)):*
> ```JavaScript
> 
> const GotoPostButton = props => {
>   let styling = 'absolute rounded-full text-base text-center py-1 px-3 border-2 border-black bg-red-link text-white '
> ```

Why do you need this variable for?
You can do:
``` className=`[all your classes as string] ${props.className}` ```


<!-- Sent from Reviewable.io -->

2021-05-20 17:24 UTC, IdanSchiller reviewed
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1)* status: all files reviewed, 4 unresolved discussions (waiting on @nir2002)

___
*[src/templates/WeeklyUpdatePostTemplate.jsx, line 42 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-Ma8acNyEWdHQZoBCXqb:-Ma9hfh23Tdh4qiYMTs_:b-mzey4t) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0ce0d64798214c9a0748fe8aa0d253b387d3bc9a/src/templates/WeeklyUpdatePostTemplate.jsx#L42)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

as discussed
</blockquote></details>

changed it to a Gap component
___
*[src/templates/WeeklyUpdatePostTemplate.jsx, line 43 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-Ma8ai1u4b-yBcU4E6NB:-Ma9hlbL6G5456rk_eOP:b66qtbb) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/0ce0d64798214c9a0748fe8aa0d253b387d3bc9a/src/templates/WeeklyUpdatePostTemplate.jsx#L43)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

as discussed
</blockquote></details>

removed the MAIN_CONTENT
___
*[src/templates/weekly-update.jsx, line 67 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-Ma06i4_9pyONvZokwCC-r2-67:-Ma9g2Ld3WmuN5WSq6Cb:ba3gsd1) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e826f742444a066da328b01759c0bb95b97522a1/src/templates/weekly-update.jsx#L67)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

I checked in the code, its still there.
</blockquote></details>

I'm so sorry, didn't realized you were talking about the " render only 8 items" comment. It is now REMOVED.
___
*[src/templates/weekly-update.jsx, line 132 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-Ma06i4_9pyONvZokwCC-r2-132:-Ma9n2n68CY5PHCt0UeB:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e826f742444a066da328b01759c0bb95b97522a1/src/templates/weekly-update.jsx#L132)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

Its a must :) and already configured in the project
</blockquote></details>

Done.
___
*[src/templates/weekly-update.jsx, line 75 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-Ma9c3-_EjkTJudhlFNH:-Ma9gucv272qrE8jthx7:bwfi1x8) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/f74bbd42cba67a00f0524546c060a50b65c855ac/src/templates/weekly-update.jsx#L75)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

Why do you need this variable for?
You can do:
``` className=`[all your classes as string] ${props.className}` ```


</blockquote></details>

You are right! changed that


<!-- Sent from Reviewable.io -->

2021-05-21 06:12 UTC, nir2002 requested changes
> Reviewed 5 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1)* status: all files reviewed, 3 unresolved discussions (waiting on @IdanSchiller)

___
*[gatsby-config.js, line 61 at r7](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-MaCYIjhDAo1PzLRLf-b:-MaCYIji6rvmrDOqO-3J:b-jc6o6f) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/d214fe35d76c66299f62ce796be0933f3b78928d/gatsby-config.js#L61)):*
> ```JavaScript
>           'gatsby-remark-copy-linked-files',
>           'gatsby-remark-prismjs',
>           'gatsby-plugin-sharp',
> ```

What does this plugin do?
___
*[.vscode/settings.json, line 1 at r7](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-MaCY8hUD0t0OLVc9Eih:-MaCY8hWBSOT3Z4qZ3Ff:b-jopa8) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/d214fe35d76c66299f62ce796be0933f3b78928d/.vscode/settings.json#L1)):*
> ```JSON
> {
> ```

put `.vscode` under `.gitignore`
___
*[content/weekly-update/ניסיון.md, line 1 at r7](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-MaCXypOCH2gjV1kL3f1:-MaCXypPDw3szV3Y_6E4:b-4ko74o) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/d214fe35d76c66299f62ce796be0933f3b78928d/content/weekly-update/ניסיון.md#L1)):*
> ```Markdown
> ---
> ```

lets not push this file


<!-- Sent from Reviewable.io -->

2021-05-21 06:31 UTC, IdanSchiller reviewed
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1)* status: all files reviewed, 3 unresolved discussions (waiting on @nir2002)

___
*[gatsby-config.js, line 61 at r7](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-MaCYIjhDAo1PzLRLf-b:-MaCbRfKBv7GhmRiy3w2:b-xjt5z7) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/d214fe35d76c66299f62ce796be0933f3b78928d/gatsby-config.js#L61)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

What does this plugin do?
</blockquote></details>

it was for reading images from the frontmatter, but it's not there anymore
___
*[.vscode/settings.json, line 1 at r7](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-MaCY8hUD0t0OLVc9Eih:-MaCbGLx1V4SH00BPC5y:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/d214fe35d76c66299f62ce796be0933f3b78928d/.vscode/settings.json#L1)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

put `.vscode` under `.gitignore`
</blockquote></details>

Done.
___
*[content/weekly-update/ניסיון.md, line 1 at r7](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-MaCXypOCH2gjV1kL3f1:-MaCbIvw9x9TRBhFAQeP:b-itnpgf) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/d214fe35d76c66299f62ce796be0933f3b78928d/content/weekly-update/ניסיון.md#L1)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

lets not push this file
</blockquote></details>

add it to <code>.gitignoe</code> as well


<!-- Sent from Reviewable.io -->

2021-05-21 07:47 UTC, nir2002 requested changes
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1)* status: 176 of 180 files reviewed, 3 unresolved discussions (waiting on @IdanSchiller and @nir2002)

___
*[gatsby-config.js, line 61 at r7](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-MaCYIjhDAo1PzLRLf-b:-MaCt9KE31LgYe8sWHy0:bn3zhjy) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/d214fe35d76c66299f62ce796be0933f3b78928d/gatsby-config.js#L61)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

it was for reading images from the frontmatter, but it's not there anymore
</blockquote></details>

so why do we need it?
___
*[.vscode/settings.json, line 1 at r7](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-MaCY8hUD0t0OLVc9Eih:-MaCt34QCC2yuLQzqCTY:b-lylcmh) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/d214fe35d76c66299f62ce796be0933f3b78928d/.vscode/settings.json#L1)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

Done.
</blockquote></details>

now remove the file :)
___
*[content/weekly-update/ניסיון.md, line 1 at r7](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-MaCXypOCH2gjV1kL3f1:-MaCt5aE29n7aM8aYqB6:b-vj4wn) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/d214fe35d76c66299f62ce796be0933f3b78928d/content/weekly-update/ניסיון.md#L1)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

add it to <code>.gitignoe</code> as well
</blockquote></details>

so remove the file in remote


<!-- Sent from Reviewable.io -->

2021-05-21 08:06 UTC, IdanSchiller reviewed
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1)* status: 174 of 181 files reviewed, 3 unresolved discussions (waiting on @nir2002)

___
*[gatsby-config.js, line 61 at r7](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-MaCYIjhDAo1PzLRLf-b:-MaCwoBx0emObEgaUVqc:b-wmft0c) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/d214fe35d76c66299f62ce796be0933f3b78928d/gatsby-config.js#L61)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

so why do we need it?
</blockquote></details>

we don't, I don't know why it appears in here, I've deleted this line in the last commit
___
*[.vscode/settings.json, line 1 at r7](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-MaCY8hUD0t0OLVc9Eih:-MaCxS8J-sdNuxdKW094:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/d214fe35d76c66299f62ce796be0933f3b78928d/.vscode/settings.json#L1)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

now remove the file :)
</blockquote></details>

Done.
___
*[content/weekly-update/ניסיון.md, line 1 at r7](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-MaCXypOCH2gjV1kL3f1:-MaCxUOS9llRjCLO7V8S:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/d214fe35d76c66299f62ce796be0933f3b78928d/content/weekly-update/ניסיון.md#L1)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

so remove the file in remote
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-21 08:08 UTC, IdanSchiller reviewed
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1)* status: 174 of 181 files reviewed, 3 unresolved discussions (waiting on @nir2002)

___
*[gatsby-config.js, line 61 at r7](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1#-MaCYIjhDAo1PzLRLf-b:-MaCxame6jeQcnqQIfaB:b-k3qjwk) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/d214fe35d76c66299f62ce796be0933f3b78928d/gatsby-config.js#L61)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

we don't, I don't know why it appears in here, I've deleted this line in the last commit
</blockquote></details>

It doesn't appears in the remote as well


<!-- Sent from Reviewable.io -->

2021-05-21 08:28 UTC, nir2002 approved these changes
> Reviewed 4 of 4 files at r8, 1 of 1 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IdanSchiller)



<!-- Sent from Reviewable.io -->

2021-05-22 16:13 UTC, merged