seo
nir2002/ganyeledteva-gatsby pull request #12
Opened 2021-06-23 20:47 UTC by IdanSchiller

2021-06-23 21:44 UTC, nir2002 requested changes
> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12)* status: all files reviewed, 33 unresolved discussions (waiting on @IdanSchiller)

___
*[gatsby-node.js, line 25 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-Mcuh909CmfnBUXbYBNF:-Mcuh909CmfnBUXbYBNG:b-bosonp) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/gatsby-node.js#L25)):*
> ```JavaScript
>       Object.prototype.hasOwnProperty.call(node.frontmatter, 'title')
>     ) {
>       if (parsedFilePath.dir===ganDirName){
> ```

spaces

`if (parsedFilePath.dir === ganDirName){`
___
*[gatsby-node.js, line 27 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuhHCSBQQ64bhMtlaI:-McuhHCSBQQ64bhMtlaJ:b-ne96xv) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/gatsby-node.js#L27)):*
> ```JavaScript
>       if (parsedFilePath.dir===ganDirName){
>         slug = `/${parsedFilePath.dir}/${parsedFilePath.name}`;
>       }else{
> ```

space here as well
} else {

I think prettier is not working on this file, am I right?
___
*[content/gan/tzona.md, line 21 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuhVM68nuFEZK4I0mO:-McuhVM68nuFEZK4I0mP:b-m8o6f) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/content/gan/tzona.md#L21)):*
> ```Markdown
> התפריט נבנה ע"י נטלי שמש - תזונאית קלינית מוסמכת.
> 
> > [לצפייה בתפריט לחץ כאן](../assets/pics/uploads/menu.pdf)
> ```

why under pics?
let create a more meaningful path
assets/uploads/files?
assets/uploads/pdfs?
___
*[data/SiteConfig.js, line 3 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuhiYV6HnmRZuKSpKj:-McuhiYV6HnmRZuKSpKk:bopuq2h) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L3)):*
> ```JavaScript
> const config = {
>   siteTitle: 'גן ילדי הטבע הדמוקרטי', // Site title.
>   siteTitleShort: 'GA Starter', // Short site title for homescreen (PWA). Preferably should be under 12 characters to prevent truncation.
> ```

change this as well :)
גן ילדי הטבע
___
*[data/SiteConfig.js, line 4 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuhnQl7MXE9Y_fCHkD:-McuhnQl7MXE9Y_fCHkE:bji9y6k) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L4)):*
> ```JavaScript
>   siteTitle: 'גן ילדי הטבע הדמוקרטי', // Site title.
>   siteTitleShort: 'GA Starter', // Short site title for homescreen (PWA). Preferably should be under 12 characters to prevent truncation.
>   siteTitleAlt: 'GatsbyJS Advanced Starter', // Alternative site title for SEO.
> ```

and this
___
*[data/SiteConfig.js, line 6 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuhsiNBeiu9WbZTjTu:-McuhsiNBeiu9WbZTjTv:bji9y6k) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L6)):*
> ```JavaScript
>   siteTitleAlt: 'GatsbyJS Advanced Starter', // Alternative site title for SEO.
>   siteLogo: '/logos/logo-1024.png', // Logo used for SEO and manifest.
>   siteUrl: 'https://gatsby-advanced-starter-demo.netlify.com', // Domain of your website without pathPrefix.
> ```

and this
___
*[data/SiteConfig.js, line 8 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuhuRW3yaA46h3URo3:-McuhuRX7BX-BZ9zuHsV:b-6bguuy) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L8)):*
> ```JavaScript
>   siteUrl: 'https://gatsby-advanced-starter-demo.netlify.com', // Domain of your website without pathPrefix.
>   pathPrefix: '/', // Prefixes all links. For cases when deployed to example.github.io/gatsby-advanced-starter/.
>   siteDescription: 'A GatsbyJS starter with Advanced design in mind.', // Website description used for RSS feeds/meta description tag.
> ```

for this I will give you a description once ready
___
*[data/SiteConfig.js, line 9 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuhxHd3FP7SJMDl1sB:-McuhxHd3FP7SJMDl1sC:bam1pda) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L9)):*
> ```JavaScript
>   pathPrefix: '/', // Prefixes all links. For cases when deployed to example.github.io/gatsby-advanced-starter/.
>   siteDescription: 'A GatsbyJS starter with Advanced design in mind.', // Website description used for RSS feeds/meta description tag.
>   siteRss: '/rss.xml', // Path to the RSS file.
> ```

I think we should delete this
___
*[data/SiteConfig.js, line 10 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-Mcuhzn34vzztp2p1Lsl:-Mcuhzn34vzztp2p1Lsm:bhvsz5l) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L10)):*
> ```JavaScript
>   siteDescription: 'A GatsbyJS starter with Advanced design in mind.', // Website description used for RSS feeds/meta description tag.
>   siteRss: '/rss.xml', // Path to the RSS file.
>   siteRssTitle: 'Gatsby Advanced Starter RSS feed', // Title of the RSS feed
> ```

leave it blank, just make sure we are not using it somewhere
___
*[data/SiteConfig.js, line 11 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-Mcui-iO1-CEvpvngoqY:-Mcui-iO1-CEvpvngoqZ:bhvsz5l) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L11)):*
> ```JavaScript
>   siteRss: '/rss.xml', // Path to the RSS file.
>   siteRssTitle: 'Gatsby Advanced Starter RSS feed', // Title of the RSS feed
>   siteFBAppID: '1825356251115265', // FB Application ID for using app insights
> ```

leave it blank, just make sure we are not using it somewhere
___
*[data/SiteConfig.js, line 12 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-Mcui1YX2FafMzVEChvs:-Mcui1YY0_BmsS5gNMIa:bhvsz5l) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L12)):*
> ```JavaScript
>   siteRssTitle: 'Gatsby Advanced Starter RSS feed', // Title of the RSS feed
>   siteFBAppID: '1825356251115265', // FB Application ID for using app insights
>   googleAnalyticsID: 'UA-47311644-5', // GA tracking ID.
> ```

leave it blank, just make sure we are not using it somewhere
___
*[data/SiteConfig.js, line 13 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuiDop-8SQFmnc6s9i:-McuiDop-8SQFmnc6s9j:b2kz5vm) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L13)):*
> ```JavaScript
>   siteFBAppID: '1825356251115265', // FB Application ID for using app insights
>   googleAnalyticsID: 'UA-47311644-5', // GA tracking ID.
>   disqusShortname: 'https-vagr9k-github-io-gatsby-advanced-starter', // Disqus shortname.
> ```

whats this for?
___
*[data/SiteConfig.js, line 16 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuiHJgAv4JcCTCyE9k:-McuiHJgAv4JcCTCyE9l:b-lu8aw5) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L16)):*
> ```JavaScript
>   dateFromFormat: 'YYYY-MM-DD', // Date format used in the frontmatter.
>   dateFormat: 'DD/MM/YYYY', // Date format for display.
>   postsPerPage: 4, // Amount of posts displayed per listing page.
> ```

do you use this? if not then remove it
although it will be nice to use it, no?
___
*[data/SiteConfig.js, line 17 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuiOx-CkxSdHhlKekX:-McuiOx-CkxSdHhlKekY:b-l6mwxj) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/d [...]

2021-06-24 07:44 UTC, IdanSchiller reviewed
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12)* status: all files reviewed, 33 unresolved discussions (waiting on @nir2002)

___
*[gatsby-node.js, line 25 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-Mcuh909CmfnBUXbYBNF:-Mcwp17QE6gTHioMwyx4:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/gatsby-node.js#L25)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

spaces

`if (parsedFilePath.dir === ganDirName){`
</blockquote></details>

Done.
___
*[gatsby-node.js, line 27 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuhHCSBQQ64bhMtlaI:-Mcwp9pKEkL3kW4eT_mX:bw5i4uq) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/gatsby-node.js#L27)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

space here as well
} else {

I think prettier is not working on this file, am I right?
</blockquote></details>

yeah it doesn't work...
___
*[content/gan/tzona.md, line 21 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuhVM68nuFEZK4I0mO:-McwpVGB2USkJ-zJlvjC:bfwnuey) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/content/gan/tzona.md#L21)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

why under pics?
let create a more meaningful path
assets/uploads/files?
assets/uploads/pdfs?
</blockquote></details>

this is where the CMS puts it, I just uploaded it to 'media assets' in the admin console. We need to check out how to control where the file goes
___
*[data/SiteConfig.js, line 3 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuhiYV6HnmRZuKSpKj:-McwqHMh82UkYGMSOuV4:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L3)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

change this as well :)
גן ילדי הטבע
</blockquote></details>

Done.
___
*[data/SiteConfig.js, line 4 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuhnQl7MXE9Y_fCHkD:-McwqMwm9GC6eUhQxHzM:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L4)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

and this
</blockquote></details>

Done.
___
*[data/SiteConfig.js, line 6 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuhsiNBeiu9WbZTjTu:-McwqnJl1MBLZt-Rfqe_:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L6)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

and this
</blockquote></details>

Done.
___
*[data/SiteConfig.js, line 8 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuhuRW3yaA46h3URo3:-Mcwqq7m4ngreOQ3JUnf:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L8)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

for this I will give you a description once ready
</blockquote></details>

Done.
___
*[data/SiteConfig.js, line 9 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuhxHd3FP7SJMDl1sB:-McwqsaeBGsBI89jbTz-:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L9)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

I think we should delete this
</blockquote></details>

Done.
___
*[data/SiteConfig.js, line 10 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-Mcuhzn34vzztp2p1Lsl:-Mcwr-u42ULOCNyJAzyq:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L10)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

leave it blank, just make sure we are not using it somewhere
</blockquote></details>

Done.
___
*[data/SiteConfig.js, line 11 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-Mcui-iO1-CEvpvngoqY:-McwrCQiANXDaZSegJ-R:b-88dxpf) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L11)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

leave it blank, just make sure we are not using it somewhere
</blockquote></details>

It is used in the SEO for a meta tag, but it is okay to leave it blank according to this:
<code>
      <meta
        property="fb:app_id"
        content={config.siteFBAppID ? config.siteFBAppID : ""}
      />
</code>

so I blanked it
___
*[data/SiteConfig.js, line 12 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-Mcui1YX2FafMzVEChvs:-Mcwrk178OT5RmSXzUh1:bg09fbc) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L12)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

leave it blank, just make sure we are not using it somewhere
</blockquote></details>

we are using it in the google analytics plugin in <code>gatsby.config</code> 
___
*[data/SiteConfig.js, line 13 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuiDop-8SQFmnc6s9i:-Mcws-Ac48-WcSQnFTXJ:bu6mosd) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L13)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

whats this for?
</blockquote></details>

no clue, I think we are not using Disqus anymore
___
*[data/SiteConfig.js, line 16 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuiHJgAv4JcCTCyE9k:-McwsBOjCTr_J-cf7_65:b-qp1qw5) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L16)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

do you use this? if not then remove it
although it will be nice to use it, no?
</blockquote></details>

I am not using it, the only place I see we can use it is in the 'weekly-update' page where we render 8 posts in a gird, but I don't think it is qualifies as a site configuration. removed it
___
*[data/SiteConfig.js, line 17 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuiOx-CkxSdHhlKekX:-McwsdqJ9DoWp9T9PLDe:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L17)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[data/SiteConfig.js, line 18 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuiPZr-veJYhORNir2:-McwseSX6KUyKjbdt0m7:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L18)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[data/SiteConfig.js, line 19 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuiQCS8Ho-PvJGIaXD:-Mcwsnkh0pOqXdXvx9gc:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L19)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[dat [...]

2021-06-24 08:32 UTC, nir2002 requested changes
> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12)* status: all files reviewed, 6 unresolved discussions (waiting on @IdanSchiller)

___
*[content/gan/tzona.md, line 21 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuhVM68nuFEZK4I0mO:-Mcx88gkA3RXna26eOHm:bgilnzo) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/content/gan/tzona.md#L21)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

this is where the CMS puts it, I just uploaded it to 'media assets' in the admin console. We need to check out how to control where the file goes
</blockquote></details>

its under `config.yml` file in the `media_folder` attribute
you can read about the configuration here: https://www.netlifycms.org/docs/configuration-options/
___
*[data/SiteConfig.js, line 12 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-Mcui1YX2FafMzVEChvs:-Mcx6XL56jgAVLDqVZDv:b-ng360t) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L12)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

we are using it in the google analytics plugin in <code>gatsby.config</code> 
</blockquote></details>

but its not a real id, so leave it blank
___
*[data/SiteConfig.js, line 13 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuiDop-8SQFmnc6s9i:-Mcx6an-0JeUnohzv2Xq:b7lza9r) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L13)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

no clue, I think we are not using Disqus anymore
</blockquote></details>

so delete it 
___
*[src/components/Page/PageHeader.jsx, line 10 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-Mcx6pMLEfis1W6f-PA3:-Mcx6pMLEfis1W6f-PA4:b-2cttwj) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/459527ca996442e47edf7280c15d378fbf6a9e8a/src/components/Page/PageHeader.jsx#L10)):*
> ```JavaScript
>   backgroundPatternClass,
> }) {
>   return title ? (
> ```

return early

```
if(!title) {
  return null
}

return (<Page.Header...)
```
___
*[src/components/PostListing/PostListing.jsx, line 24 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McujvbiAv7WoNACOLRF:-Mcx8P56EWZrFA2IIhdg:b-3amr17) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/src/components/PostListing/PostListing.jsx#L24)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

I don't see ae are using it anywhere, I think it an exampled you've used in the past. can I delete it?
</blockquote></details>

if not used then yes, sure
___
*[src/components/TextTitle/TextTitle.jsx, line 4 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-Mculgl1BXs78cglT7D9:-Mcx7jvd8ysNYq0uX4kP:bou3gqk) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/src/components/TextTitle/TextTitle.jsx#L4)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

You've created this component and you use it in the Home component for the SectionCards you render
</blockquote></details>

Oh cool then ;)


<!-- Sent from Reviewable.io -->

2021-06-24 13:46 UTC, IdanSchiller reviewed
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12)* status: all files reviewed, 6 unresolved discussions (waiting on @nir2002)

___
*[content/gan/tzona.md, line 21 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuhVM68nuFEZK4I0mO:-McyGEkq3HLZZuymL_uj:bxk2pdk) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/content/gan/tzona.md#L21)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

its under `config.yml` file in the `media_folder` attribute
you can read about the configuration here: https://www.netlifycms.org/docs/configuration-options/

</blockquote></details>

changed the path for 'media_folder' to what we said on WA
___
*[data/SiteConfig.js, line 12 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-Mcui1YX2FafMzVEChvs:-McxVp863aZzHdL7BLdx:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L12)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

but its not a real id, so leave it blank
</blockquote></details>

Done.
___
*[data/SiteConfig.js, line 13 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McuiDop-8SQFmnc6s9i:-McxVrQKCGliOuOWiFBw:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/data/SiteConfig.js#L13)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

so delete it 
</blockquote></details>

Done.
___
*[src/components/Page/PageHeader.jsx, line 10 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-Mcx6pMLEfis1W6f-PA3:-McxWFYS-gzqAs5x0T53:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/459527ca996442e47edf7280c15d378fbf6a9e8a/src/components/Page/PageHeader.jsx#L10)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

return early

```
if(!title) {
  return null
}

return (<Page.Header...)
```
</blockquote></details>

Done.
___
*[src/components/PostListing/PostListing.jsx, line 24 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-McujvbiAv7WoNACOLRF:-McxWQAM4KomcxbZ0hYp:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/src/components/PostListing/PostListing.jsx#L24)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

if not used then yes, sure
</blockquote></details>

Done.
___
*[src/components/TextTitle/TextTitle.jsx, line 4 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12#-Mculgl1BXs78cglT7D9:-McxWTlI9izD2d7FqQQV:b32vhw) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/6ba1232ab27e951102baab45d1981615f3d46e71/src/components/TextTitle/TextTitle.jsx#L4)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

Oh cool then ;)
</blockquote></details>

:)


<!-- Sent from Reviewable.io -->

2021-06-29 07:47 UTC, nir2002 approved these changes
> Reviewed 6 of 6 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IdanSchiller)



<!-- Sent from Reviewable.io -->

2021-06-29 07:47 UTC, nir2002 approved these changes
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IdanSchiller)



<!-- Sent from Reviewable.io -->

2021-06-30 09:42 UTC, merged