feature/gan
nir2002/ganyeledteva-gatsby pull request #4
Opened 2021-06-01 09:58 UTC by IdanSchiller

2021-06-01 18:47 UTC, nir2002 requested changes
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4)* status: all files reviewed, 27 unresolved discussions (waiting on @IdanSchiller)

___
*[gatsby-node.js, line 50 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7lEymARZ3N79_2-n4:-Mb7lEynE0fYSA_LViSm:b-eeai73) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/gatsby-node.js#L50)):*
> ```JavaScript
> exports.createPages = async ({ graphql, actions }) => {
>   const { createPage } = actions;
>   const weeklyPostPage = path.resolve("src/templates/WeeklyUpdatePostTemplate.jsx"); // This should be weekly-update post page
> ```

1. you can delete my comment
2. add `./` as a prefix to the path
___
*[gatsby-node.js, line 51 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7lVob6eoAkJeC845-:-Mb7lVob6eoAkJeC8450:b-puyu8h) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/gatsby-node.js#L51)):*
> ```JavaScript
>   const { createPage } = actions;
>   const weeklyPostPage = path.resolve("src/templates/WeeklyUpdatePostTemplate.jsx"); // This should be weekly-update post page
>   const weeklyUpdatePage = path.resolve("./src/components/Pages/Weekly-Update/weekly-update.jsx");
> ```

please create an `index.js` file under `Weekly-Update` folder that exports default from `weekly-update.js`, then you will be able to write this path: "./src/componets/Pages/Weekly-Update"

Also, `Pages` should be `pages` and `Weekly-Update` should be `WeeklyUpdate` (I know that it might be my own mistake :) )
___
*[gatsby-node.js, line 52 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7neJ04xdK5H11iYQM:-Mb7neJ1-t6572o8aoHU:boyc8wt) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/gatsby-node.js#L52)):*
> ```JavaScript
>   const weeklyPostPage = path.resolve("src/templates/WeeklyUpdatePostTemplate.jsx"); // This should be weekly-update post page
>   const weeklyUpdatePage = path.resolve("./src/components/Pages/Weekly-Update/weekly-update.jsx");
>   const ganPostPage = path.resolve("./src/templates/GanPostTemplate.jsx"); // This should be weekly-update post page
> ```

delete my cooment
___
*[gatsby-node.js, line 53 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7nie87lnlGYIU4V0Y:-Mb7nie87lnlGYIU4V0Z:b-dzlroo) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/gatsby-node.js#L53)):*
> ```JavaScript
>   const weeklyUpdatePage = path.resolve("./src/components/Pages/Weekly-Update/weekly-update.jsx");
>   const ganPostPage = path.resolve("./src/templates/GanPostTemplate.jsx"); // This should be weekly-update post page
>   const ganPage = path.resolve("./src/components/Pages/Gan/Gan.jsx");
> ```

same thing with index.js
___
*[gatsby-node.js, line 118 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7nn233YJn2Bf4DwxM:-Mb7nn233YJn2Bf4DwxN:brnfx3e) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/gatsby-node.js#L118)):*
> ```JavaScript
> 
>     createPage({
>       path: edge.node.fields.slug, // this should be the title in the md file
> ```

you can remove the comment
___
*[gatsby-node.js, line 122 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7npqU3x_qdl4_S3Zq:-Mb7npqU3x_qdl4_S3Zr:brnfx3e) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/gatsby-node.js#L122)):*
> ```JavaScript
>       context: {
>         slug: edge.node.fields.slug,
>         // all the below data can be used to create prev/next post buttons
> ```

you can remove the comment
___
*[gatsby-node.js, line 136 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7o-a60sV8wNlwXEfR:-Mb7o-a60sV8wNlwXEfS:b-467x9j) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/gatsby-node.js#L136)):*
> ```JavaScript
> 
>   /** We will use this for the weekly-updates blog */
>   // Post page creating
> ```

remove the comment
___
*[gatsby-node.js, line 137 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7oN8B6md6wFTmh8hs:-Mb7oN8B6md6wFTmh8ht:biphpnh) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/gatsby-node.js#L137)):*
> ```JavaScript
>   /** We will use this for the weekly-updates blog */
>   // Post page creating
>   postsEdges.forEach((edge) => {
> ```

How does postEdges here different from the weekly-update ones?
___
*[gatsby-node.js, line 138 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7nzUqEvE9H1RPFP2_:-Mb7nzUqEvE9H1RPFP2a:b-467x9j) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/gatsby-node.js#L138)):*
> ```JavaScript
>   // Post page creating
>   postsEdges.forEach((edge) => {
>     // Create post pages
> ```

remove the comment
___
*[gatsby-node.js, line 141 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7nvomBIXfxNEWOCOm:-Mb7nvomBIXfxNEWOCOn:brnfx3e) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/gatsby-node.js#L141)):*
> ```JavaScript
> 
>     createPage({
>       path: edge.node.fields.slug, // this should be the title in the md file
> ```

you can remove the comment
___
*[tailwind.config.js, line 27 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7ojeb-psOUOre_zbb:-Mb7ofz46hrOLtgZRt9y:b-sqmqto) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/tailwind.config.js#L27)):*
> ```JavaScript
>           header1weekly : '#8cf8e7' ,
>           header2weekly : '#8ddad5',
>           headerGanPost: '#96e6a1',
> ```

I think we should rename those to `weeklyHeader1`, `weeklyHeader2` etc. 
what do you think? does it make more sense?

and maybe even `weeklyPageHeader1`..
___
*[tailwind.config.js, line 28 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7oYKT8OEG7fp4iBgg:-Mb7oYKT8OEG7fp4iBgh:b-an78tn) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/tailwind.config.js#L28)):*
> ```JavaScript
>           header2weekly : '#8ddad5',
>           headerGanPost: '#96e6a1',
>           
> ```

what are all this dots?
___
*[tailwind.config.js, line 35 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7oy1TBsTRE_4KAwyB:-Mb7oy1TBsTRE_4KAwyC:b-iqj24m) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/tailwind.config.js#L35)):*
> ```JavaScript
>         },
>         blue:{
>           header1Gan: '#8cf8e7',
> ```

same here `GanPageHeader1`
___
*[src/components/Pages/Gan/Gan.jsx, line 24 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7qENYBZn-eDVDxbLY:-Mb7qENYBZn-eDVDxbLZ:b-y6dt4k) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/src/components/Pages/Gan/Gan.jsx#L24)):*
> ```JavaScript
>   });
> 
>   const headerMdPost = postList.filter(
> ```

can we rename to `postHeader`?
___
*[src/components/Pages/Gan/Gan.jsx, line 25 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7pYtW-qDG2n9E8jto:-Mb7pYtX1dFeV_7KvDC9:b-440kgg) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/src/components/Pages/Gan/Gan.jsx#L25)):*
> ```JavaScript
> 
>   const headerMdPost = postList.filter(
>     (post) => post.title === "גן ילדי הטבע הדמוקרטי"
> ```

Why? is this the main page?
Isn't any other way to figure this out? I want to let them the ability to change the text without breaking stuff.

If this is the only way then this have  [...]

2021-06-02 09:28 UTC, IdanSchiller reviewed
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4)* status: all files reviewed, 27 unresolved discussions (waiting on @IdanSchiller and @nir2002)

___
*[gatsby-node.js, line 50 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7lEymARZ3N79_2-n4:-Mb8YHwH4il_Wek32EL6:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/gatsby-node.js#L50)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

1. you can delete my comment
2. add `./` as a prefix to the path
</blockquote></details>

Done.
___
*[gatsby-node.js, line 51 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7lVob6eoAkJeC845-:-MbB0VYDCiKhTkUt0kbX:bjzzfxt) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/gatsby-node.js#L51)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

please create an `index.js` file under `Weekly-Update` folder that exports default from `weekly-update.js`, then you will be able to write this path: "./src/componets/Pages/Weekly-Update"

Also, `Pages` should be `pages` and `Weekly-Update` should be `WeeklyUpdate` (I know that it might be my own mistake :) )
</blockquote></details>

you mean create  a file <code>WeeklyUpdate/index.js</code> with the following content: 
<code>
import WeeklyUpdate from "./weekly-update";

export default WeeklyUpdate;
</code>
?

if so, it doesn't work
___
*[gatsby-node.js, line 52 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7neJ04xdK5H11iYQM:-Mb8YQZA2oBFZr-gOULo:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/gatsby-node.js#L52)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

delete my cooment
</blockquote></details>

Done.
___
*[gatsby-node.js, line 118 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7nn233YJn2Bf4DwxM:-Mb8YZGKERE-mGZhRFdN:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/gatsby-node.js#L118)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

you can remove the comment
</blockquote></details>

Done.
___
*[gatsby-node.js, line 122 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7npqU3x_qdl4_S3Zq:-Mb8YbbaAfh4kY-mfBuR:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/gatsby-node.js#L122)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

you can remove the comment
</blockquote></details>

Done.
___
*[gatsby-node.js, line 136 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7o-a60sV8wNlwXEfR:-Mb8YgDz2o-8Npe4N-BD:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/gatsby-node.js#L136)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

remove the comment
</blockquote></details>

Done.
___
*[gatsby-node.js, line 137 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7oN8B6md6wFTmh8hs:-MbAmj-SAVHl1VYEte2f:b-p5nw) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/gatsby-node.js#L137)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

How does postEdges here different from the weekly-update ones?
</blockquote></details>

it's not, I've fixed it and combined the creation of pages according to the 'dir' they came from ('gan' / 'weekly-update')
___
*[gatsby-node.js, line 138 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7nzUqEvE9H1RPFP2_:-Mb8Ykro21V9L_pEF4KD:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/gatsby-node.js#L138)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

remove the comment
</blockquote></details>

Done.
___
*[gatsby-node.js, line 141 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7nvomBIXfxNEWOCOm:-Mb8YlOY5OuS1dboQ6VM:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/gatsby-node.js#L141)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

you can remove the comment
</blockquote></details>

Done.
___
*[tailwind.config.js, line 27 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7ojeb-psOUOre_zbb:-MbAzo0U-9V7HaQNGksg:buiq45x) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/tailwind.config.js#L27)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

I think we should rename those to `weeklyHeader1`, `weeklyHeader2` etc. 
what do you think? does it make more sense?

and maybe even `weeklyPageHeader1`..
</blockquote></details>

see the comment about the kebabCase
___
*[tailwind.config.js, line 28 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7oYKT8OEG7fp4iBgg:-MbArAAU9xKKXje8XQjX:bxcbbs5) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/tailwind.config.js#L28)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

what are all this dots?
</blockquote></details>

I don't know, I can't see them in the code
___
*[src/components/Pages/Gan/Gan.jsx, line 24 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7qENYBZn-eDVDxbLY:-Mb8ZCok5GCdSaNSEikA:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/src/components/Pages/Gan/Gan.jsx#L24)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

can we rename to `postHeader`?
</blockquote></details>

Done.
___
*[src/components/Pages/Gan/Gan.jsx, line 26 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7qdmV81negizJNEp7:-MbAucHf29zB8AEtRCAZ:b7w8ut1) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/src/components/Pages/Gan/Gan.jsx#L26)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

I am a bit confused, what is this exactly? Are you trying to find the main page and take the header data out of it?

We should have this data when we are creating the page in gatsby-node, don't we?
</blockquote></details>

The header information is defined in <code>/content/gan/index.md</code> file (opening hours act.), so I'm retrieving the information from that section( md file).
the <code>post.title === "גן ילדי הטבע הדמוקרטי"</code> is the indicator for that file.

I've now changed it to check if the section filename is 'index' , and I've defined that name ('index') in the config file (because I use it in 2 different files).
so now they can write whatever they want in the <code>/content/gan/index.md</code> and it will appear in the gan page header.
or I could hard code the text in the header (like in the weekly-update page).
hard code it? do something else? or leave it with that change (filename indicator)?
___
*[src/components/Pages/Gan/Gan.jsx, line 62 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7rSzKAScFXH2jYBdk:-MbAsmYB7brdayNfTfPP:b-box0pk) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/src/components/Pages/Gan/Gan.jsx#L62)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

I think Post is kind of a strange word here since it isn't really a post, maybe section is bett [...]

2021-06-02 09:44 UTC, nir2002 requested changes
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4)* status: all files reviewed, 19 unresolved discussions (waiting on @IdanSchiller)

___
*[gatsby-node.js, line 51 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7lVob6eoAkJeC845-:-MbB5oxjBya6A5tSlA7T:blu3n00) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/gatsby-node.js#L51)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

you mean create  a file <code>WeeklyUpdate/index.js</code> with the following content: 
<code>
import WeeklyUpdate from "./weekly-update";

export default WeeklyUpdate;
</code>
?

if so, it doesn't work
</blockquote></details>

lets talk about this in zoom
___
*[gatsby-node.js, line 55 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-MbB3LKo65wUROsCP_IP:-MbB3LKo65wUROsCP_IQ:b-cv5lph) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e25aa48b4add8eb270a28bd38f0d09a2d23e4f48/gatsby-node.js#L55)):*
> ```JavaScript
>   const weeklyPostPage = path.resolve("./src/templates/WeeklyUpdatePostTemplate.jsx"); 
>   const weeklyUpdatePage = path.resolve("./src/components/Pages/WeeklyUpdate/weekly-update.jsx");
>   const ganPostPage = path.resolve("./src/templates/GanSectionTemplate.jsx");
> ```

genSectionPage, or ganSubPage
___
*[gatsby-node.js, line 118 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-MbB3Atn65qfoXVWNR0A:-MbB3Ato4ucDSY6gDyMR:b77z85e) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e25aa48b4add8eb270a28bd38f0d09a2d23e4f48/gatsby-node.js#L118)):*
> ```JavaScript
>   /** We will use this for the weekly-updates blog */
>   postsEdges.forEach((edge, index) => {
>     if(edge.node.fields.dir===ganDirName){
> ```

use spaced if(x === y)
___
*[gatsby-node.js, line 127 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-MbB3FLN5dU72B2MPI8l:-MbB3FLN5dU72B2MPI8m:bb7od0r) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e25aa48b4add8eb270a28bd38f0d09a2d23e4f48/gatsby-node.js#L127)):*
> ```JavaScript
>     });
>   }
>   else if(edge.node.fields.dir===weeklyUpdateDirName){
> ```

same
___
*[tailwind.config.js, line 27 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7ojeb-psOUOre_zbb:-MbB5GdW3EG2U0-ED36h:b-lncodb) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/tailwind.config.js#L27)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

see the comment about the kebabCase
</blockquote></details>

see my comment there
___
*[tailwind.config.js, line 28 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7oYKT8OEG7fp4iBgg:-MbB3kiU4qrVthKbhJrm:b-t4xt77) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/tailwind.config.js#L28)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

I don't know, I can't see them in the code
</blockquote></details>

I think its some spaces you editor creates, try to delete this line and create a new one
___
*[data/SiteConfig.js, line 45 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-MbB5NRI6bS-7r-ZAiTj:-MbB5NRI6bS-7r-ZAiTk:b-ewvcs2) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e25aa48b4add8eb270a28bd38f0d09a2d23e4f48/data/SiteConfig.js#L45)):*
> ```JavaScript
>   themeColor: '#c62828', // Used for setting manifest and progress theme colors.
>   backgroundColor: '#e0e0e0', // Used for setting manifest background color.
>   ganPageHeaderInfoMdFileName : 'index', // the file name of the .md file that holds the information for the 'Gan' page header
> ```

I would like if you mention in the comment why there is such a file in the first place, but first lets talk about this in zoom (see my next comment)
___
*[src/components/Pages/Gan/Gan.jsx, line 26 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7qdmV81negizJNEp7:-MbB5fiSAPJQyq8AUWkA:bgci30d) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/src/components/Pages/Gan/Gan.jsx#L26)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

The header information is defined in <code>/content/gan/index.md</code> file (opening hours act.), so I'm retrieving the information from that section( md file).
the <code>post.title === "גן ילדי הטבע הדמוקרטי"</code> is the indicator for that file.

I've now changed it to check if the section filename is 'index' , and I've defined that name ('index') in the config file (because I use it in 2 different files).
so now they can write whatever they want in the <code>/content/gan/index.md</code> and it will appear in the gan page header.
or I could hard code the text in the header (like in the weekly-update page).
hard code it? do something else? or leave it with that change (filename indicator)?
</blockquote></details>

lets talk about it in zoom
___
*[src/components/Pages/WeeklyUpdate/index.js, line 3 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-MbB5uaj7BYigwxnxJ80:-MbB5uaj7BYigwxnxJ81:b-la2qlk) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e25aa48b4add8eb270a28bd38f0d09a2d23e4f48/src/components/Pages/WeeklyUpdate/index.js#L3)):*
> ```JavaScript
> import WeeklyUpdate from "./weekly-update";
> 
> export default WeeklyUpdate;
> ```

by the way I think you can do:

export { default } from "./weekly-update"
___
*[src/components/Pages/WeeklyUpdate/weekly-update.jsx, line 37 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-MbB62eO0SyE65UNaQi2:-MbB62eO0SyE65UNaQi3:b-my4g5w) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e25aa48b4add8eb270a28bd38f0d09a2d23e4f48/src/components/Pages/WeeklyUpdate/weekly-update.jsx#L37)):*
> ```JavaScript
>           title="העדכון השבועי"
>           subtitle="מתוך הכרה בחשיבות הקשר שבין המשולש- ילד/ה-בית-גן נשלח אליכם ההורים בכל סוף שבוע עדכון שבועי ובו אנו משתפות אתכם בחוויות המשותפות שלנו ממהלך השבוע, מעדכנות בפרטים חשובים ומאפשרות גם לכם להיות חלק מהעשייה בגן."
>           backgroundColorClass="bg-gradient-to-r from-green-weeklyUpdate-header1 to-green-weeklyUpdate-header2"
> ```

see my comment in kebab-case
___
*[src/templates/GanPostTemplate.jsx, line 12 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7sHptBXc-sYvcVwBx:-MbB4Uy0EzS0t9IuMxH_:b1elgpy) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/src/templates/GanPostTemplate.jsx#L12)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

mdx is the mdx file that is used for this specific section, and allMdx are all the mdx files in the <code>/gan</code> directory, so I could render the nav menu in the bottom
</blockquote></details>

so rename it somehow
`mdxSectionDate`, `mdxPagesData`? think of something that we can look at 2 years from now and understand quickly :)
___
*[src/templates/GanPostTemplate.jsx, line 32 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7scMq2YFkF1-uJN-S:-MbB4lIMEmVCe8gBTPpf:b-1meyer) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/src/templates/GanPostTemplate.jsx#L32)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

<code>yellow-headerBorder</code> is defined in the <code>tailwind.config.js</code> file so it's an object <code>yellow : { headerBorder: '#99999' }</code> and could not be <code>yellow : { header-border: '#99999' }</code>.

in order to make it kebab-case, I need to do: <code>yellow : { header: {border: '#99999' }</code> which mean make the code uglier in <code>tailwind.config.js</code>.
should I do so?

after we decide the course of action, I will change all the name  [...]

2021-06-02 10:12 UTC, IdanSchiller reviewed
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4)* status: all files reviewed, 19 unresolved discussions (waiting on @IdanSchiller and @nir2002)

___
*[gatsby-node.js, line 55 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-MbB3LKo65wUROsCP_IP:-MbBByOtCK1_Gnn8qQTe:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e25aa48b4add8eb270a28bd38f0d09a2d23e4f48/gatsby-node.js#L55)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

genSectionPage, or ganSubPage
</blockquote></details>

Done.
___
*[gatsby-node.js, line 118 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-MbB3Atn65qfoXVWNR0A:-MbBC3604K3EpDrXVncp:bnyebvl) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e25aa48b4add8eb270a28bd38f0d09a2d23e4f48/gatsby-node.js#L118)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

use spaced if(x === y)
</blockquote></details>

Done. thought the prettier extension will take care of it. 
___
*[gatsby-node.js, line 127 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-MbB3FLN5dU72B2MPI8l:-MbBC4W-BOAUPswhdGoE:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e25aa48b4add8eb270a28bd38f0d09a2d23e4f48/gatsby-node.js#L127)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[tailwind.config.js, line 27 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7ojeb-psOUOre_zbb:-MbBAkGnEVSZMAS_pdPI:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/tailwind.config.js#L27)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

see my comment there
</blockquote></details>

Done.
___
*[tailwind.config.js, line 28 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7oYKT8OEG7fp4iBgg:-MbBCEg90lzoweo23C0D:beu1dnp) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/tailwind.config.js#L28)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

I think its some spaces you editor creates, try to delete this line and create a new one
</blockquote></details>

is it still there? I changed the file a bit
___
*[tailwind.config.js, line 35 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7oy1TBsTRE_4KAwyB:-MbBAjKe21XDfN7ycOzO:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/tailwind.config.js#L35)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

same here `GanPageHeader1`
</blockquote></details>

Done.
___
*[src/components/Pages/WeeklyUpdate/weekly-update.jsx, line 37 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-MbB62eO0SyE65UNaQi2:-MbBAukj3Ye3jzTQunoB:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e25aa48b4add8eb270a28bd38f0d09a2d23e4f48/src/components/Pages/WeeklyUpdate/weekly-update.jsx#L37)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

see my comment in kebab-case
</blockquote></details>

Done.
___
*[src/templates/GanPostTemplate.jsx, line 12 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7sHptBXc-sYvcVwBx:-MbBBOXf5wfcCUqzr8cz:b1afham) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/src/templates/GanPostTemplate.jsx#L12)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

so rename it somehow
`mdxSectionDate`, `mdxPagesData`? think of something that we can look at 2 years from now and understand quickly :)
</blockquote></details>

I'm not sure it's possible, this is how the graghQL queries the md file...
![image.png](https://files.reviewableusercontent.io/images/reviewable/58664272/eeadg5-DY0oIFVvqsQZdzNc7/image.png)
___
*[src/templates/GanPostTemplate.jsx, line 32 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7scMq2YFkF1-uJN-S:-MbBBq801HsuwF6E1-e3:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/src/templates/GanPostTemplate.jsx#L32)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

try do: `yellow: {'header-border' : '#99999'}`
</blockquote></details>

Done.
___
*[src/templates/GanPostTemplate.jsx, line 36 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7siBUAEKRsA2QN75_:-MbBBrTh4b7yp671fm9P:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/src/templates/GanPostTemplate.jsx#L36)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

same here for class name
</blockquote></details>

Done.
___
*[src/templates/GanPostTemplate.jsx, line 53 at r1](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-Mb7srzm26cpE3MdZYHW:-MbBBses-tk4dktHDKyp:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/89aa110d0566d86cfe6cbd29c47133250dae4c2f/src/templates/GanPostTemplate.jsx#L53)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[src/templates/GanSectionTemplate.jsx, line 22 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-MbB4Mvo1IoyDU-smZxs:-MbBBm9J6ZvPV6AeVXmN:b8yeina) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e25aa48b4add8eb270a28bd38f0d09a2d23e4f48/src/templates/GanSectionTemplate.jsx#L22)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

no commented code, delete it
</blockquote></details>

yeah sorry missed that. deleted
___
*[src/templates/GanSectionTemplate.jsx, line 77 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-MbB4z2uEWAXIYskVYl2:-MbBBtx-8qDR6vBLl3Fy:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e25aa48b4add8eb270a28bd38f0d09a2d23e4f48/src/templates/GanSectionTemplate.jsx#L77)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

remove if not used
</blockquote></details>

Done.
___
*[src/templates/GanSectionTemplate.jsx, line 78 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-MbB574W3XUs7V5Lcf0R:-MbBBv5WE79jRNwaYbyn:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e25aa48b4add8eb270a28bd38f0d09a2d23e4f48/src/templates/GanSectionTemplate.jsx#L78)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

if you used active here (which I like) then change `currSectionTitle` to `activeSectionTitle`, be consistent
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-02 12:41 UTC, nir2002 requested changes
> Reviewed 6 of 6 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4)* status: all files reviewed, 1 unresolved discussion (waiting on @IdanSchiller)

___
*[data/SiteConfig.js, line 45 at r4](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-MbBjNyWBCWZhaXnl0rQ:-MbBjNyWBCWZhaXnl0rR:b9yx4xz) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/28f95a408b4aa7322d0bbf94eb7b319bab09f769/data/SiteConfig.js#L45)):*
> ```JavaScript
>   themeColor: '#c62828', // Used for setting manifest and progress theme colors.
>   backgroundColor: '#e0e0e0', // Used for setting manifest background color.
>   ganMainPageDataMdFileName : 'index', // the file name of the .md file that holds the information for the 'Gan' page header
> ```

don't forget to change the comment


<!-- Sent from Reviewable.io -->

2021-06-02 13:14 UTC, IdanSchiller reviewed
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4)* status: 11 of 14 files reviewed, 1 unresolved discussion (waiting on @nir2002)

___
*[data/SiteConfig.js, line 45 at r2](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-MbB5NRI6bS-7r-ZAiTj:-MbBqlJYA0HWUQgMzV85:b-o1aijt) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/e25aa48b4add8eb270a28bd38f0d09a2d23e4f48/data/SiteConfig.js#L45)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

I would like if you mention in the comment why there is such a file in the first place, but first lets talk about this in zoom (see my next comment)
</blockquote></details>

handled
___
*[data/SiteConfig.js, line 45 at r4](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4#-MbBjNyWBCWZhaXnl0rQ:-MbBqpon2IwX3V97NZG5:b-o1aijt) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/28f95a408b4aa7322d0bbf94eb7b319bab09f769/data/SiteConfig.js#L45)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

don't forget to change the comment
</blockquote></details>

handled


<!-- Sent from Reviewable.io -->

2021-06-02 14:20 UTC, nir2002 approved these changes
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IdanSchiller)



<!-- Sent from Reviewable.io -->

2021-06-02 14:32 UTC, merged