feature/home
nir2002/ganyeledteva-gatsby pull request #8
Opened 2021-06-07 11:04 UTC by IdanSchiller

2021-06-17 21:22 UTC, nir2002 requested changes
> Reviewed 2 of 6 files at r2, 2 of 16 files at r3, 19 of 20 files at r4, 24 of 25 files at r5.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8)* status: 28 of 29 files reviewed, 9 unresolved discussions (waiting on @IdanSchiller)

___
*[package.json, line 51 at r4](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McQdekz9VCtDVV2VjkO:-McQdel-9xsguem5-mmK:b-gsf26j) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/43201c484864a62cd526a2431fd11bdfc3f1d59e/package.json#L51)):*
> ```JSON
>     "react-dom": "^17.0.1",
>     "react-helmet": "^6.1.0",
>     "react-image-size": "^1.0.4",
> ```

what is it?
___
*[tailwind.config.js, line 6 at r4](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McQdjHu68v5E0Y0w9JB:-McQdjHu68v5E0Y0w9JC:b-tnrwo1) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/43201c484864a62cd526a2431fd11bdfc3f1d59e/tailwind.config.js#L6)):*
> ```JavaScript
>   theme: {
>     flex:{
>       '3': '0 0 33.333333%',
> ```

whats this? 🤨
___
*[tailwind.config.js, line 20 at r4](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McQdrS99DSBgsK81ojc:-McQdrS99DSBgsK81ojd:b44u34) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/43201c484864a62cd526a2431fd11bdfc3f1d59e/tailwind.config.js#L20)):*
> ```JavaScript
>       },
>       flex:{
>         '3': '0 0 33.333333%',
> ```

😨
___
*[content/team/רעות.md, line 7 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McQp8Yo-FMQGPy24NHw:-McQp8Yo-FMQGPy24NHx:b-vuriyi) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/content/team/רעות.md#L7)):*
> ```Markdown
> img: /img/pics/14690886_10210986222993055_7974594543976767151_n.jpg
> index: 17
> unique: 11
> ```

what is unique for?
___
*[src/components/TeamGrid/TeamGrid.jsx, line 6 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McQq1Gs9nldVtG5OwmC:-McQq1Gs9nldVtG5OwmD:b8mwh6r) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L6)):*
> ```JavaScript
> import { XIcon } from "@heroicons/react/outline";
> import { MDXRenderer } from "gatsby-plugin-mdx";
> const mainDummyTitle = "צוות הגן";
> ```

1. put a line space before this const
2. Why `Dummy`?
___
*[src/components/TeamGrid/TeamGrid.jsx, line 7 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McQqBATEiSESrc9m7pp:-McQqBATEiSESrc9m7pq:b-8maymj) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L7)):*
> ```JavaScript
> import { MDXRenderer } from "gatsby-plugin-mdx";
> const mainDummyTitle = "צוות הגן";
> const diamondSideLength = 27;
> ```

What does it mean? what is side length?
___
*[src/layout/index.jsx, line 16 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McQofRe9LOT5X98G0pL:-McQoFPAD-wIe_agxZBI:b-1x6g3s) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/layout/index.jsx#L16)):*
> ```JavaScript
> import favicon from "~static/logos/favicon.png";
> 
> const navigation = [
> ```

lets take this out to a json config file
I did it at the begin to move quickly
___
*[src/layout/index.jsx, line 70 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McQno2F7Dvz6twlaw75:-McQno2F7Dvz6twlaw76:b-luhm20) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/layout/index.jsx#L70)):*
> ```JavaScript
>                   </div>
>                 </div>
>                 <div className="text-sm my-auto hidden sm:flex flex-row">
> ```

how much time will it take to make it configurable via a dedicated MD file?
___
*[src/layout/index.jsx, line 142 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McQnzNi27sGyETfx7YY:-McQnzNi27sGyETfx7YZ:b-ehv2ei) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/layout/index.jsx#L142)):*
> ```JavaScript
> );
> 
> const FBIcon = () => <FontAwesomeIcon icon={faFacebookF} />;
> ```

why do you need it? just use it as it is


<!-- Sent from Reviewable.io -->

2021-06-18 05:42 UTC, nir2002 requested changes
> Reviewed 1 of 25 files at r5.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8)* status: all files reviewed, 26 unresolved discussions (waiting on @IdanSchiller)

___
*[src/components/TeamGrid/TeamGrid.jsx, line 30 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McSZQZhBWDr03IxuAoC:-McSZQZhBWDr03IxuAoD:b-qmh2mm) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L30)):*
> ```JavaScript
> 
>   let teamList = [];
>   data.allMdx.edges.forEach((employeeEdge) => {
> ```

you can use map instead

```
let teamlist = data.allMdx.edges.map((employeeEdge)=> ({ ... });
```

and improvement will be

```
const {body} = employeeEdge.node
const {title, firstname, lastname, img, index} = employeeEdge.node.frontmatter;

return {
title,
firstname,
lastname
img...
}
```
___
*[src/components/TeamGrid/TeamGrid.jsx, line 42 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McS_Jbn0EClmliOFfWq:-McS_Jbn0EClmliOFfWr:b-gsgg65) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L42)):*
> ```JavaScript
> 
>   teamList.sort((a, b) => (a.index > b.index ? 1 : -1));
>   let splittedTeamList = [];
> ```

what do you mean by split? split how?
___
*[src/components/TeamGrid/TeamGrid.jsx, line 44 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McS_5m39uv450KUw1KL:-McS_5m39uv450KUw1KM:b-6720r1) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L44)):*
> ```JavaScript
>   let splittedTeamList = [];
>   let mainDummyDiamond = { title: mainDummyTitle };
>   let DummyDiamond = { title: "", isDummy: true };
> ```

why capital D?
what the difference between main and not main?
___
*[src/components/TeamGrid/TeamGrid.jsx, line 46 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McS_QiwC7YT9bintvZ4:-McS_QiwC7YT9bintvZ5:buzp7f3) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L46)):*
> ```JavaScript
>   let DummyDiamond = { title: "", isDummy: true };
>   splittedTeamList.push([teamList[0], mainDummyDiamond, teamList[1]]);
>   let teamListWithoutFirstTwo = teamList.slice(2);
> ```

explain in a comment why do you need it. or better, by the variable name, its pretty obvious from the code on the right that its the team list without the first 2, but its not informative on why do you need it
___
*[src/components/TeamGrid/TeamGrid.jsx, line 47 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McS_fXQ7644SFJE0fjv:-McS_fXQ7644SFJE0fjw:b-pc4dvh) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L47)):*
> ```JavaScript
>   splittedTeamList.push([teamList[0], mainDummyDiamond, teamList[1]]);
>   let teamListWithoutFirstTwo = teamList.slice(2);
>   let shouldTakeTwoEmployees = true;
> ```

explain why do need this variable
___
*[src/components/TeamGrid/TeamGrid.jsx, line 60 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McSa9pS4TB6uQnFTPGb:-McSa9pS4TB6uQnFTPGc:b-nedmm3) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L60)):*
> ```JavaScript
>   }
> 
>   const oneBeforeLastSubArrLen =
> ```

why do you need it? and are you certain it will be defined? you assume a lot of thing on this code and it can crash when doing changes to the data pretty easily, you should treat errors so it won't crash the app
___
*[src/components/TeamGrid/TeamGrid.jsx, line 62 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McSaBWJBHAOqrjohUd5:-McSaBWK5Q2RKcGhZna0:b2nif8j) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L62)):*
> ```JavaScript
>   const oneBeforeLastSubArrLen =
>     splittedTeamList[splittedTeamList.length - 2].length;
>   const lastSubArrLen = splittedTeamList[splittedTeamList.length - 1].length;
> ```

why
___
*[src/components/TeamGrid/TeamGrid.jsx, line 68 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McSaOyU391FM3dtBPwn:-McSaOyU391FM3dtBPwo:b33yiig) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L68)):*
> ```JavaScript
>       splittedTeamList[splittedTeamList.length - 1].push(DummyDiamond);
>   } else if (oneBeforeLastSubArrLen === 3 && lastSubArrLen === 1)
>     splittedTeamList[splittedTeamList.length - 1].push(DummyDiamond);
> ```

so, first, as you saw from my comments, the code is pretty hard to understand
I want to be able to look at it in 1 year from now and understand easily what is going here

put some effort into making things more clear, add comments where needed, the encapsulate all of this logic into a function

If possible, make the code shorter (like using the map I suggested) - less to read=more maintainable (in my opinion)
___
*[src/components/TeamGrid/TeamGrid.jsx, line 79 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McSbhUU2AKmTJhLlJiM:-McSbhUU2AKmTJhLlJiN:bkap1fx) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L79)):*
> ```JavaScript
>               style={{
>                 marginTop:
>                   index === 0 ? "auto" : `-${(diamondSideLength - 1) / 2}vw`,
> ```

you can use mt-top in className and percentage instead of vw, if it doesn't work lets do zoom about it and try to understand
___
*[src/components/TeamGrid/TeamGrid.jsx, line 99 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McSbxLd9iXEgJd8jjN7:-McSbxLd9iXEgJd8jjN8:bsktu39) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L99)):*
> ```JavaScript
> }
> 
> const EmployeeCardDesktop = ({ details }) => {
> ```

I rather you call it `data` instead of `details`
___
*[src/components/TeamGrid/TeamGrid.jsx, line 102 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McSc12RA2yxpbKPamxe:-McSc12RA2yxpbKPamxf:ba73xw7) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L102)):*
> ```JavaScript
>   const { title, imgPath, body, firstName, lastName, isDummy } = details;
>   const [open, setOpen] = useState(false);
>   return (
> ```

space it with a new line
___
*[src/components/TeamGrid/TeamGrid.jsx, line 115 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McScKsd88M-a7Cy12aZ:-McScKseBbpj-79_y8Wz:b-5eyjf8) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L115)):*
> ```JavaScript
>           className="relative mt-auto mr-auto"
>           style={{
>             width: `${diamondSideLength}vw`,
> ```

same, lets try to together to avoid it
___
*[src/components/TeamGrid/TeamGrid.jsx, line 147 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McScPH23iGfvhrbyLIA:-McScPH3DGAd9TaC3PXy:bb7esdr) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L147)):*
> ```JavaScript
> };
> 
> const EmployeeCardMobile = ({ details }) => {
> ```

data
___
*[src/components/TeamGrid/TeamGrid.jsx, line 175 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McScmw40NmkLAltxFZf:-McScmw40NmkLAltxFZg:b-7lp89u) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65 [...]

2021-06-20 11:07 UTC, IdanSchiller reviewed
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8)* status: all files reviewed, 26 unresolved discussions (waiting on @nir2002)

___
*[package.json, line 51 at r4](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McQdekz9VCtDVV2VjkO:-McTElh-1wUabZ0EWgb7:b-vvr6ks) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/43201c484864a62cd526a2431fd11bdfc3f1d59e/package.json#L51)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

what is it?
</blockquote></details>

sorry, removed
___
*[tailwind.config.js, line 6 at r4](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McQdjHu68v5E0Y0w9JB:-McTEpj55DrEMZPa_RgP:b-ksh2zs) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/43201c484864a62cd526a2431fd11bdfc3f1d59e/tailwind.config.js#L6)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

whats this? 🤨
</blockquote></details>

sorry as well, removed
___
*[tailwind.config.js, line 20 at r4](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McQdrS99DSBgsK81ojc:-McTEsyQ4udUeVwrFSDP:bb7od0r) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/43201c484864a62cd526a2431fd11bdfc3f1d59e/tailwind.config.js#L20)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

😨
</blockquote></details>

same
___
*[content/team/רעות.md, line 7 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McQp8Yo-FMQGPy24NHw:-McTF5aT6tbarDZnKKvU:b1bye1j) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/content/team/רעות.md#L7)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

what is unique for?
</blockquote></details>

very sorry it was for testing, removed
___
*[src/components/TeamGrid/TeamGrid.jsx, line 6 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McQq1Gs9nldVtG5OwmC:-MccTyLM3nYnmRFZvYl2:b7sz0wt) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L6)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

1. put a line space before this const
2. Why `Dummy`?
</blockquote></details>

1. Done.
2. because it's not a real employee diamond, just sort of a placeholder. changed the name to "mainEmptyDiamondTitle".
___
*[src/components/TeamGrid/TeamGrid.jsx, line 7 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McQqBATEiSESrc9m7pp:-MccURP05t2Zd09vVItY:b-h2c047) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L7)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

What does it mean? what is side length?
</blockquote></details>

אורך צלע (של המעוין)
___
*[src/components/TeamGrid/TeamGrid.jsx, line 30 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McSZQZhBWDr03IxuAoC:-McTGqMa6m3G7BuMRtnA:bup27mx) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L30)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

you can use map instead

```
let teamlist = data.allMdx.edges.map((employeeEdge)=> ({ ... });
```

and improvement will be

```
const {body} = employeeEdge.node
const {title, firstname, lastname, img, index} = employeeEdge.node.frontmatter;

return {
title,
firstname,
lastname
img...
}
```
</blockquote></details>

Done.
 (I took inspiration from how you handled <code>postEdges</code> on "Weekly-apdate" page .
I wondered why you would use <code>forEach</code> instead of <code>map</code>, figured there was a reason...
___
*[src/components/TeamGrid/TeamGrid.jsx, line 42 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McS_Jbn0EClmliOFfWq:-MccaTJFD-OmTAvte8YA:bzgvbtp) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L42)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

what do you mean by split? split how?
</blockquote></details>

Changed that to more informative name
___
*[src/components/TeamGrid/TeamGrid.jsx, line 44 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McS_5m39uv450KUw1KL:-MccY9fZ8WaLuTDYnub-:bkkuz9g) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L44)):*
> why capital D?

by mistake

> what the difference between main and not main?

main in the one with the "Gan Team" title, not main is just a placeholder so the grid layout (row of 3 diamond followed by a row of 2 diamond) won't break
___
*[src/components/TeamGrid/TeamGrid.jsx, line 46 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McS_QiwC7YT9bintvZ4:-MccYcrt1gzeDYjuvnr6:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L46)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

explain in a comment why do you need it. or better, by the variable name, its pretty obvious from the code on the right that its the team list without the first 2, but its not informative on why do you need it
</blockquote></details>

Done.
___
*[src/components/TeamGrid/TeamGrid.jsx, line 47 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McS_fXQ7644SFJE0fjv:-MccYhIP3p0gt7oomyxM:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L47)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

explain why do need this variable
</blockquote></details>

Done.
___
*[src/components/TeamGrid/TeamGrid.jsx, line 60 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McSa9pS4TB6uQnFTPGb:-Mcd5DB6CEoud7dsI94l:b-cfec6k) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L60)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

why do you need it? and are you certain it will be defined? you assume a lot of thing on this code and it can crash when doing changes to the data pretty easily, you should treat errors so it won't crash the app
</blockquote></details>

Explained in a comment
___
*[src/components/TeamGrid/TeamGrid.jsx, line 62 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McSaBWJBHAOqrjohUd5:-Mcd5IEY9ZYm7_iiGhlT:b-u3s7re) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L62)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

why
</blockquote></details>

Explained in a comment
___
*[src/components/TeamGrid/TeamGrid.jsx, line 68 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McSaOyU391FM3dtBPwn:-Mcd5P9H9SefkPLVKF-C:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L68)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

so, first, as you saw from my comments, the code is pretty hard to understand
I want to be able to look at it in 1 year from now and understand easily what is going here

put some effort into making things more clear, add comments where needed, the encapsulate all of this logic into a function

If possible, make the code shorter (like using the ma [...]

2021-06-21 10:46 UTC, nir2002 requested changes
> Reviewed 21 of 21 files at r6.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8)* status: all files reviewed, 15 unresolved discussions (waiting on @IdanSchiller)

___
*[src/components/TeamGrid/TeamGrid.jsx, line 7 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McQqBATEiSESrc9m7pp:-Mci61zn5XOX_cGEuvLe:bfp9u9o) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L7)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

אורך צלע (של המעוין)
</blockquote></details>

so it should be `diamonSideEdgeLength`
___
*[src/components/TeamGrid/TeamGrid.jsx, line 30 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McSZQZhBWDr03IxuAoC:-Mci6VQa72eHM9S4HnS0:bmriw85) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L30)):*
<details><summary><i>Previously, IdanSchiller wrote…</i></summary><blockquote>

Done.
 (I took inspiration from how you handled <code>postEdges</code> on "Weekly-apdate" page .
I wondered why you would use <code>forEach</code> instead of <code>map</code>, figured there was a reason...
</blockquote></details>

I did?
I know why, because I copy paste this code from somewhere 😅
Anyway, shame on me, I'll fix that
___
*[src/components/TeamGrid/TeamGrid.jsx, line 28 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-Mci6A5k4lhsty-OI7bb:-Mci6A5k4lhsty-OI7bc:b-tdrktp) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/aed78aa11dc9bf6890814bc3bf48f09282f7ea49/src/components/TeamGrid/TeamGrid.jsx#L28)):*
> ```JavaScript
>       }
>     }
>   `);
> ```

insert line space here, even two!
___
*[src/components/TeamGrid/TeamGrid.jsx, line 59 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-Mci75kXBCUqHHtoaNyq:-Mci75kXBCUqHHtoaNyr:bv5us9b) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/aed78aa11dc9bf6890814bc3bf48f09282f7ea49/src/components/TeamGrid/TeamGrid.jsx#L59)):*
> ```JavaScript
>           return (
>             <div
>               key={index}
> ```

if possible try to avoid using index for keys
___
*[src/components/TeamGrid/TeamGrid.jsx, line 66 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-Mci77WFDxmVys2E6Xol:-Mci77WFDxmVys2E6Xom:bv5us9b) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/aed78aa11dc9bf6890814bc3bf48f09282f7ea49/src/components/TeamGrid/TeamGrid.jsx#L66)):*
> ```JavaScript
>               }}
>             >
>               {singleSplittedTeamList.map((employeeData, index) => (
> ```

if possible try to avoid using index for keys
___
*[src/components/TeamGrid/TeamGrid.jsx, line 75 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-Mci7LRd6lWfDKGXO2um:-Mci7LRd6lWfDKGXO2un:bv5us9b) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/aed78aa11dc9bf6890814bc3bf48f09282f7ea49/src/components/TeamGrid/TeamGrid.jsx#L75)):*
> ```JavaScript
> 
>       <div className="block md:hidden w-full grid grid-cols-2 gap-2 text-center px-2">
>         {teamList.map((employeeData, index) => {
> ```

if possible try to avoid using index for keys
___
*[src/components/TeamGrid/TeamGrid.jsx, line 212 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-Mci8NVs93-KVKvn-sWE:-Mci8NVs93-KVKvn-sWF:b-tw14u9) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/aed78aa11dc9bf6890814bc3bf48f09282f7ea49/src/components/TeamGrid/TeamGrid.jsx#L212)):*
> ```JavaScript
>  * splits the team list into sub arrays of 2's and 3's,
>  * to create a grid layout of rows of 3 diamonds followed by a row of 2 diamonds and so on...
>  * assumptions: @param:teamList length >= 2, meaning there are at least 2 .md file of gan's worker
> ```

workers :)
___
*[src/components/TeamGrid/TeamGrid.jsx, line 216 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-Mci8_WbEgq9rcBhiRQ2:-Mci8_WbEgq9rcBhiRQ3:b-ek6psq) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/aed78aa11dc9bf6890814bc3bf48f09282f7ea49/src/components/TeamGrid/TeamGrid.jsx#L216)):*
> ```JavaScript
> const prepareTeamListForDiamondGrid = (teamList) => {
>   let teamListSplitToSubArrs = []; // this will hold the team list split to sub arrays of 2's and 3's
>   let mainEmptyDiamond = { title: mainEmptyDiamondTitle };
> ```

1. add a comment here // this is for the first row middle diamond that holds text only
by the way, we don't we put it as an md file as well just without any image?

2. why let and not const?
___
*[src/components/TeamGrid/TeamGrid.jsx, line 217 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-Mci94U88eZQX_kDjFIt:-Mci94U88eZQX_kDjFIu:b-9wc4vg) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/aed78aa11dc9bf6890814bc3bf48f09282f7ea49/src/components/TeamGrid/TeamGrid.jsx#L217)):*
> ```JavaScript
>   let teamListSplitToSubArrs = []; // this will hold the team list split to sub arrays of 2's and 3's
>   let mainEmptyDiamond = { title: mainEmptyDiamondTitle };
>   let placeholderEmptyDiamond = { title: "", isEmpty: true };
> ```

why let and not const?
___
*[src/components/TeamGrid/TeamGrid.jsx, line 218 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-Mci9EoU9JcjVhivCX8S:-Mci9EoU9JcjVhivCX8T:b-7s4sqq) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/aed78aa11dc9bf6890814bc3bf48f09282f7ea49/src/components/TeamGrid/TeamGrid.jsx#L218)):*
> ```JavaScript
>   let mainEmptyDiamond = { title: mainEmptyDiamondTitle };
>   let placeholderEmptyDiamond = { title: "", isEmpty: true };
>   let firstGridRow = [teamList[0], mainEmptyDiamond, teamList[1]]; // first row with the Gan's managers and the empty diamond with the grid title
> ```

const
___
*[src/components/TeamGrid/TeamGrid.jsx, line 222 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-Mci9NMC0hV0Ap5CB3gO:-Mci9NMC0hV0Ap5CB3gP:bdkcptq) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/aed78aa11dc9bf6890814bc3bf48f09282f7ea49/src/components/TeamGrid/TeamGrid.jsx#L222)):*
> ```JavaScript
> 
>   let shouldBeGridRowOfTwo = true; // for the splitting process, flag to indicate if row of 2 employees or 3.
>   let ganEmployeesWithoutManagers = teamList.slice(2);
> ```

1. rename to ganEMployeesExcludeManagers
2. place in a comment Managers - Tzachi and Ahinoham
___
*[src/components/TeamGrid/TeamGrid.jsx, line 244 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-MciA7pcBqKzeM1rYrEm:-MciA7pcBqKzeM1rYrEn:b-tw14u9) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/aed78aa11dc9bf6890814bc3bf48f09282f7ea49/src/components/TeamGrid/TeamGrid.jsx#L244)):*
> ```JavaScript
>  * OR
>  * one before last row length == 2 AND last row length != 3
>  * assumptions: @param:teamListSplitToSubArrs length >= 2, meaning there are at least 3 .md file of gan's worker
> ```

workers :)
___
*[src/components/TeamGrid/TeamGrid.jsx, line 246 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-MciAG857S5W6azjfvA3:-MciAG857S5W6azjfvA4:bext7mk) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/aed78aa11dc9bf6890814bc3bf48f09282f7ea49/src/components/TeamGrid/TeamGrid.jsx#L246)):*
> ```JavaScript
>  * assumptions: @param:teamListSplitToSubArrs length >= 2, meaning there are at least 3 .md file of gan's worker
>  */
> const fillInEmptyDiamondsIfNeeded = (teamListSplitToSubArrs) => {
> ```

say, why don't we just put empty md files where the empty diamonds should be and just render them? this way is more customizable
___
*[src/layout/index.jsx, line 16 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McQofRe9LOT5X98G0pL:-Mci7vhGBX_xTdzp3IvN:b-qbu3pw) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/layout/index.jsx#L16)):*
<deta [...]

2021-06-21 22:06 UTC, IdanSchiller reviewed
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8)* status: all files reviewed, 15 unresolved discussions (waiting on @IdanSchiller and @nir2002)

___
*[src/components/TeamGrid/TeamGrid.jsx, line 7 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McQqBATEiSESrc9m7pp:-MckU6hK8eyDnH0QRzHb:bbts8f3) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/components/TeamGrid/TeamGrid.jsx#L7)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

so it should be `diamonSideEdgeLength`
</blockquote></details>

Done.


(for the record - the translation was from here...
https://www.morfix.co.il/%D7%A6%D7%9C%D7%A2, so side==edge, but I see the confusion)
___
*[src/components/TeamGrid/TeamGrid.jsx, line 28 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-Mci6A5k4lhsty-OI7bb:-MckUd7C6WFrl-LL6zi8:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/aed78aa11dc9bf6890814bc3bf48f09282f7ea49/src/components/TeamGrid/TeamGrid.jsx#L28)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

insert line space here, even two!
</blockquote></details>

Done.
___
*[src/components/TeamGrid/TeamGrid.jsx, line 59 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-Mci75kXBCUqHHtoaNyq:-MckUjZh6Zy8ION65KjN:b-btjxdc) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/aed78aa11dc9bf6890814bc3bf48f09282f7ea49/src/components/TeamGrid/TeamGrid.jsx#L59)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

if possible try to avoid using index for keys
</blockquote></details>

Sure thing, but why?  🤔 (so I'll understand what I should use)
___
*[src/components/TeamGrid/TeamGrid.jsx, line 212 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-Mci8NVs93-KVKvn-sWE:-MckVVBG3BzHnlR_pX21:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/aed78aa11dc9bf6890814bc3bf48f09282f7ea49/src/components/TeamGrid/TeamGrid.jsx#L212)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

workers :)
</blockquote></details>

Done.
___
*[src/components/TeamGrid/TeamGrid.jsx, line 216 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-Mci8_WbEgq9rcBhiRQ2:-MckVsv82boYjYakkCAM:b-yq3efo) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/aed78aa11dc9bf6890814bc3bf48f09282f7ea49/src/components/TeamGrid/TeamGrid.jsx#L216)):*
1. done.
> by the way, we don't we put it as an md file as well just without any image?

We can do that, and that way they can control the <code>mainEmptyDiamondTitle</code>, let me know if you want me to do that.
2. I guess it was the academia exam period spirit that made me use the word 'let', changed that :)
___
*[src/components/TeamGrid/TeamGrid.jsx, line 217 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-Mci94U88eZQX_kDjFIt:-MckWL-QB6Vk30WSuHJe:b-7ql1td) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/aed78aa11dc9bf6890814bc3bf48f09282f7ea49/src/components/TeamGrid/TeamGrid.jsx#L217)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

why let and not const?
</blockquote></details>

fixed
___
*[src/components/TeamGrid/TeamGrid.jsx, line 218 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-Mci9EoU9JcjVhivCX8S:-MckWPA93-9yxP23xorU:b-7ql1td) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/aed78aa11dc9bf6890814bc3bf48f09282f7ea49/src/components/TeamGrid/TeamGrid.jsx#L218)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

const
</blockquote></details>

fixed
___
*[src/components/TeamGrid/TeamGrid.jsx, line 222 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-Mci9NMC0hV0Ap5CB3gO:-MckWcAb1zN4sM9265Te:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/aed78aa11dc9bf6890814bc3bf48f09282f7ea49/src/components/TeamGrid/TeamGrid.jsx#L222)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

1. rename to ganEMployeesExcludeManagers
2. place in a comment Managers - Tzachi and Ahinoham
</blockquote></details>

Done.
___
*[src/components/TeamGrid/TeamGrid.jsx, line 244 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-MciA7pcBqKzeM1rYrEm:-MckWfB1Cc3wZ42AJDRH:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/aed78aa11dc9bf6890814bc3bf48f09282f7ea49/src/components/TeamGrid/TeamGrid.jsx#L244)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

workers :)
</blockquote></details>

Done.
___
*[src/components/TeamGrid/TeamGrid.jsx, line 246 at r6](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-MciAG857S5W6azjfvA3:-MckWtyLBsrhacZpqAN5:b6icnd5) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/aed78aa11dc9bf6890814bc3bf48f09282f7ea49/src/components/TeamGrid/TeamGrid.jsx#L246)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

say, why don't we just put empty md files where the empty diamonds should be and just render them? this way is more customizable
</blockquote></details>

you said you will ask them if they want empty diamonds in the middle of the grid
___
*[src/layout/index.jsx, line 16 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McQofRe9LOT5X98G0pL:-Mck_WYL0jJTu4dPgcns:b-896fix) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/layout/index.jsx#L16)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

put it under SiteConfig file
</blockquote></details>

Done.
___
*[src/layout/index.jsx, line 70 at r5](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8#-McQno2F7Dvz6twlaw75:-MckYMBFBptyg86fxdk4:bz6r7ni) ([raw file](https://github.com/nir2002/ganyeledteva-gatsby/blob/02502080b2a65d819cde382d39a2dfd82315475a/src/layout/index.jsx#L70)):*
<details><summary><i>Previously, nir2002 (Nir Parisian) wrote…</i></summary><blockquote>

hmmm no, I meant the all bottom nav bar, so they can customize it if they want
</blockquote></details>

ahh okay, this code is for the 'facebook' and 'contact' buttons/
for the bottom nav bar, we'll have to make an editable file in the CMS that will be converted to a JS object, I didn't see how I can create such template in the '/admin' section, maybe I don't have permissions?


<!-- Sent from Reviewable.io -->

2021-06-22 09:34 UTC, nir2002 approved these changes
> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/nir2002/ganyeledteva-gatsby/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @IdanSchiller)



<!-- Sent from Reviewable.io -->

2021-06-22 10:09 UTC, merged